version: "3"
services: 
  dev:
    build: .
    tty: true
    stdin_open: true
    runtime: nvidia
    volumes: 
      - ./:/opt/segelectri
      - ${DATA_DIR}:/opt/dataset
    env_file: ./.env
    user: "${UID}:${GID}"
