version: "3"
services: 
  dev:
    user: "${UID}:${GID}"
    build: 
      context: .
      args: 
        ARG_UID: ${UID}
        ARG_GID: ${GID}
    tty: true
    stdin_open: true
    env_file: .env
    runtime: nvidia
    volumes: 
      - ./:/opt/segelectri:rw
      - ${DATA_DIR}:/opt/dataset:rw
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
  tvm:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: ./Dockerfile.tvm
    runtime: nvidia
    env_file: .env
    tty: true
    stdin_open: true
    volumes: 
      - ./:/opt/segelectri:rw
      - ${TVM_DIR}:/workspace:rw
      - ${DATA_DIR}:/opt/dataset:rw
    extra_hosts:
      - "raw.githubusercontent.com:185.199.108.133"
