version: "3"
services: 
  dev:
    user: "${UID}:${GID}"
    build: 
      context: .
      args: 
        ARG_UID: ${UID}
        ARG_GID: ${GID}
    tty: true
    stdin_open: true
    env_file: .env
    runtime: nvidia
    volumes: 
      - ./:/opt/segelectri:rw
      - ${DATA_DIR}:/opt/dataset:rw
